apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-oke-bg-app-deployment
spec:
  selector:
    matchLabels:
      app: sample-oke-bg-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-oke-bg-app
    spec:
      containers:
      - name: sample-oke-bg-app
        image: ams.ocir.io/axh1wuvhagpg/oci-bluegreen-oke-poc:${BUILDRUN_HASH}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          livenessProbe:
            exec:
              command:
              - cat
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
      - name: ocir-secret-prathap
