apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-oke-bg-app
  name: sample-oke-bg-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-oke-bg-app
  template:
    metadata:
      labels:
        app: sample-oke-bg-app
    spec:
      containers:
      - image: ams.ocir.io/axh1wuvhagpg/oci-bluegreen-oke-poc:${BUILDRUN_HASH}
        #imagePullPolicy: Always 
        name: sample-oke-bg-app
        ports:
          - containerPort: 80
            protocol: TCP
          livenessProbe:
            exec:
              command:
              - cat
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      imagePullSecrets:
      - name: ocir-secret-prathap
      
